### PR TITLE
Add src/dist asset directories, optimise Gulpfile

### PR DESCRIPTION
**Pull request by gmlnchv**
- Introduces `src` and `dist` directories for source and generated files respectively to follow the common convention (source files in `build` directory looked confusing).
- Adds a `clean` task
- Reduces boilerplate by using `gulp-load-plugins`
- Uses ES6 syntax
- Upgrades a few dependencies and moves some dependencies out of `devDependencies`

### CODE REVIEW

**Comment by adrexia** [comment]
Folder structure: One of the reasons the folder structure is as it is now is because Silverstripe automatically imports the css editor file into the CMS from `themes/themename/css/`. I agree its odd, but we did it this way to have out of the box compatibility with Silverstripe's assumptions about where css and js live. Build changing to src should be fine, but I think js, css, and images should stay where they are. 

I'm uncertain about the changes to the gulp file. It seems less declarative this way - I find it harder to tell by looking at the variables which modules the file uses. They are all just magicked in with the $ syntax. Do you find that easier to understand?

**Comment by gmlnchv** [comment]
Good point re the editor file! Will tweak the paths and get rid of `dist`. I do like the `gulp-load-plugins`, you don't have to specify each plugin at the top of the file (and we do use quite a few!), there are some lazy loading benefits (but I haven't looked into those specifically).

**Comment by adrexia** [comment]
I see benefit in specifying them at the top of the file (other than just boilerplate). I've found it helpful when auditing what is still used and what has been removed. But I'll think it over. Its probably worth running past others too. Could we change the `$` symbol to something less jquery-esque?

**Comment by gmlnchv** [comment]
Did some reading on SS4 and sounds like you should be able to supply a custom `editor.css` so removed `dist` for this PR. The Gulpfile is currently pushing 270 lines, so I think it's important to keep it succinct and `gulp-load-plugins` is a good way to cull a few lines. I don't have a problem with the dollar sign, I think it's a good enough namespace, it's also mentioned in the docs to that plugin. Observables use the dollar sign too 😄 !

**Comment by adrexia** [comment]
We can supply a custom editor.css file with ss3 too - but its actually broken in ss4 right now. ;) 

I'm more thinking of the other ways we could manage theme css/js in ss4, where we aren't just bolting together two ecosystems.

On a related note - I've been asked several times why observables have the dollar sign. The only answer is "convention", which gets you so far... ;)  In this case `$` could just as easily be a named variable. `load` for instance. Which might help make its intent clearer.

**Comment by gmlnchv** [comment]
Do you mean using `Requirements` for loading assets as opposed to links in template files?

Yeah, I'm sure I've seen the dollar sign in heaps of other places! Could totally be `load` - definitely better then `plugins`! It's just 4 characters vs 1 to type! 😄

**Comment by adrexia** [comment]
I've changed a couple of things, swashed and merged manually.
https://github.com/dnadesign/dna-recipe/commit/83ac16cb34471c6e05deb8cc20b7556a942e58e1

Sorry, a couple of newish things got attributed to you (the extra run sequence and the templates watching).

**Pull request closed without merging**
