### PR TITLE
Tidy up .gitignore

### PR DESCRIPTION
**Pull request by gmlnchv**
Exclude everything and only pick what we want to avoid explicitly listing composer dependencies.

### CODE REVIEW

**Comment by adrexia** [comment]
This git ignore caters to the composer installed modules.  I think they should be there by default.

**Comment by gmlnchv** [comment]
This PR achieves the same w/o listing every dependency explicitly though.

**Comment by adrexia** [comment]
@gmlnchv the committed files  is about to all change for silverstripe 4. Would you mind pulling against that branch instead?

**Comment by gmlnchv** [comment]
Can we still accept for version 3 though? Since we will still be using it for new project? Will resolve the conflicts.

**Comment by adrexia** [comment]
Merged to the 3.0 branch.

**Pull request merged**
